//! Markdown findings report.

use std::fs;
use std::path::Path;

use serde::Serialize;

use crate::Args;
use crate::assertions::CheckResult;
use crate::workload::{AllStats, ProvisionedSummary};

#[derive(Debug, Serialize)]
pub struct Report {
    pub args: Args,
    pub provisioned: ProvisionedSummary,
    pub stats: AllStats,
    pub results: Vec<CheckResult>,
    pub summary: Summary,
}

#[derive(Debug, Default, Serialize, Clone, Copy)]
pub struct Summary {
    pub passed: usize,
    pub failed: usize,
}

impl serde::Serialize for Args {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("Args", 3)?;
        st.serialize_field("threads_per_tenant", &self.threads_per_tenant)?;
        st.serialize_field("duration_secs", &self.duration_secs)?;
        st.serialize_field("report_path", &self.report_path)?;
        st.end()
    }
}

pub fn finalize(mut r: Report) -> Report {
    let passed = r.results.iter().filter(|c| c.passed).count();
    let failed = r.results.iter().filter(|c| !c.passed).count();
    r.summary = Summary { passed, failed };
    r
}

pub fn write_markdown<P: AsRef<Path>>(path: P, report: &Report) -> std::io::Result<()> {
    let mut out = String::new();
    out.push_str("# Elena tri-tenant fire-test report\n\n");
    out.push_str(&format!(
        "Generated by `elena-tri-tenant-firetest` on {}.\n\n",
        chrono::Utc::now().to_rfc3339()
    ));

    out.push_str("## Run config\n\n");
    out.push_str(&format!(
        "- threads_per_tenant: **{}** (total = {})\n- duration_secs: **{}**\n",
        report.args.threads_per_tenant,
        report.args.threads_per_tenant * 3,
        report.args.duration_secs
    ));

    out.push_str("\n## Provisioned tenants\n\n");
    out.push_str(&format!(
        "- Solen: tenant `{}`, {} workspaces\n- Hannlys: creator `{}`, buyer-pool tenant `{}`\n- Omnii: tenant `{}`, {} workspaces\n",
        report.provisioned.solen_tenant,
        report.provisioned.solen_workspaces,
        report.provisioned.hannlys_creator,
        report.provisioned.hannlys_buyer_tenant,
        report.provisioned.omnii_tenant,
        report.provisioned.omnii_workspaces
    ));

    out.push_str("\n## Per-tenant traffic\n\n");
    out.push_str("| Tenant | Started | Completed | Errors | p50 ms | p95 ms | p99 ms |\n");
    out.push_str("|---|---:|---:|---:|---:|---:|---:|\n");
    for (label, s) in [
        ("Solen", &report.stats.solen),
        ("Hannlys", &report.stats.hannlys),
        ("Omnii", &report.stats.omnii),
    ] {
        let (p50, p95, p99) = pct(&s.latency_ms);
        out.push_str(&format!(
            "| {label} | {} | {} | {} | {} | {} | {} |\n",
            s.started, s.completed, s.errors, p50, p95, p99
        ));
    }

    out.push_str(&format!(
        "\n## Assertions ({} passed / {} failed)\n\n",
        report.summary.passed, report.summary.failed
    ));
    for r in &report.results {
        let mark = if r.passed { "✓" } else { "✗" };
        out.push_str(&format!("- **{} {}** — {}\n", mark, r.name, r.detail));
    }

    out.push_str("\n## Cleanup contract\n\n");
    out.push_str(
        "Every tenant the test creates is dropped at the end via the\n\
         `DELETE /admin/v1/tenants/:id` cascading endpoint\n\
         (`crates/elena-admin/src/tenants.rs::delete_tenant`). The\n\
         cascade is enforced by Postgres `ON DELETE CASCADE` foreign\n\
         keys across `threads` → `messages` → `thread_approvals` /\n\
         `thread_usage`, plus direct cascades from `tenants` to\n\
         `workspaces`, `audit_events`, `episodes` (added in migration\n\
         `20260424000005_episodes_tenant_fk.sql`), `plugin_ownerships`,\n\
         `tenant_credentials`, `plans`, `plan_assignments`, and\n\
         `budget_state`.\n\n\
         The `cascading_delete_zero_orphans` assertion above counts\n\
         surviving rows across all 11 tenant-scoped tables and fails\n\
         the run if any tenant id leaked. Workspace-scoped DELETE\n\
         (`DELETE /admin/v1/workspaces/:id?tenant_id=…`) is also\n\
         available for finer-grained cleanup.\n",
    );

    fs::create_dir_all(path.as_ref().parent().unwrap_or_else(|| Path::new(".")))?;
    fs::write(path, out)
}

fn pct(samples: &[u64]) -> (u64, u64, u64) {
    if samples.is_empty() {
        return (0, 0, 0);
    }
    let mut s = samples.to_vec();
    s.sort_unstable();
    let pick = |q: f64| -> u64 {
        let idx = ((s.len() as f64) * q).floor() as usize;
        s[idx.min(s.len() - 1)]
    };
    (pick(0.50), pick(0.95), pick(0.99))
}
