//! Messages and content blocks.
//!
//! A [`Message`] is one row in a thread: `role`, a list of [`ContentBlock`]s,
//! and metadata. [`MessageKind`] tags the message family (assistant, user,
//! attachment, system-notice, etc.) so consumers can distinguish wire
//! messages from Elena's internal bookkeeping rows without inspecting
//! content.
//!
//! The content-block shape is wire-compatible with Anthropic's Beta messages
//! API. Key calibrations vs. the reference TS source:
//!
//! - [`ContentBlock::Thinking`] carries a required `signature` field (used
//!   by prompt-cache hashing) and optional redaction via
//!   [`ContentBlock::RedactedThinking`].
//! - `cache_control` is attached to individual blocks, not messages.
//! - [`ToolResultContent`] is untagged because Anthropic allows either a
//!   plain string or a nested block array.

use bytes::Bytes;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::{
    cache::CacheControl,
    id::{MessageId, TenantId, ThreadId, ToolCallId},
};

/// Message author. Matches the Anthropic wire role set plus Elena's internal
/// rows (which use `System`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Message from the end user.
    User,
    /// Message generated by the assistant model.
    Assistant,
    /// Internal bookkeeping row (compact boundary, local notice, etc.).
    System,
    /// Tool-result row sent back to the model.
    Tool,
}

/// The message kind — distinguishes assistant output from user input from
/// Elena's internal bookkeeping rows. Persisted as a tagged JSON object so
/// new variants can be added without a schema migration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum MessageKind {
    /// An assistant-generated reply.
    Assistant {
        /// Why the model stopped generating.
        stop_reason: Option<StopReason>,
        /// True if this "assistant" row is actually a surfaced API error
        /// (rendered like a message but representing a failure).
        #[serde(default)]
        is_api_error: bool,
    },
    /// A user-authored message.
    User,
    /// A file/image attached by the user out-of-band.
    Attachment,
    /// A previous row that has been replaced (e.g., compacted out).
    Tombstone {
        /// Human-readable reason the row was tombstoned.
        reason: String,
    },
    /// A summary of a tool-use exchange (for context compaction).
    ToolUseSummary,
    /// Elena-internal system notice.
    System(SystemMessageKind),
}

/// Sub-kind for system messages. Uses a distinct tag (`system_kind`) from
/// [`MessageKind`] so both can be flattened into the same JSON object when a
/// `MessageKind::System(...)` variant is serialized.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "system_kind", rename_all = "snake_case")]
pub enum SystemMessageKind {
    /// Boundary between pre-compact and post-compact context.
    CompactBoundary,
    /// Boundary between pre-microcompact and post-microcompact context.
    MicrocompactBoundary,
    /// Surfaced API error rendered as a system notice.
    ApiError {
        /// Classification tag from the LLM error taxonomy.
        classified_as: String,
    },
    /// Output of a user-typed local slash command.
    LocalCommand,
    /// Freeform system text (greetings, status, etc.).
    Text,
}

/// Why a model stopped generating output. Mirrors the Anthropic wire values
/// plus a `Refusal` variant for safety-filtered stops.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model finished its turn normally.
    EndTurn,
    /// The model hit the `max_tokens` limit.
    MaxTokens,
    /// The model emitted a tool-use block and is waiting for a result.
    ToolUse,
    /// The model hit a user-supplied stop sequence.
    StopSequence,
    /// The model refused to respond.
    Refusal,
    /// The model paused its turn (long-running tool in progress).
    PauseTurn,
}

/// A single content block inside a message.
///
/// Tagged via a `type` field on the wire, matching the Anthropic Beta API
/// format so blocks can be forwarded directly to the provider without
/// transformation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// Plain text.
    Text {
        /// The text body.
        text: String,
        /// Optional prompt-cache control.
        #[serde(skip_serializing_if = "Option::is_none", default)]
        cache_control: Option<CacheControl>,
    },

    /// Model reasoning (visible, with a signature that binds it to the reply).
    ///
    /// The `signature` is required by Anthropic so redacted thinking blocks
    /// can still contribute to the prompt cache hash.
    Thinking {
        /// The visible reasoning body.
        thinking: String,
        /// Signature that binds this block to the final reply.
        signature: String,
        /// Optional prompt-cache control.
        #[serde(skip_serializing_if = "Option::is_none", default)]
        cache_control: Option<CacheControl>,
    },

    /// Redacted model reasoning — opaque bytes returned when safety-filtered.
    RedactedThinking {
        /// Opaque data blob (Base64 per Anthropic). Pass through as-is.
        data: String,
    },

    /// The model requesting a tool call.
    ToolUse {
        /// Unique ID for this call; paired with [`ContentBlock::ToolResult`].
        id: ToolCallId,
        /// Tool name.
        name: String,
        /// Tool input as a JSON value.
        input: serde_json::Value,
        /// Optional prompt-cache control.
        #[serde(skip_serializing_if = "Option::is_none", default)]
        cache_control: Option<CacheControl>,
    },

    /// The result of a tool call, sent back to the model.
    ToolResult {
        /// Matches the `id` of the originating [`ContentBlock::ToolUse`].
        tool_use_id: ToolCallId,
        /// The result body.
        content: ToolResultContent,
        /// True if the tool call errored.
        #[serde(default)]
        is_error: bool,
        /// Optional prompt-cache control.
        #[serde(skip_serializing_if = "Option::is_none", default)]
        cache_control: Option<CacheControl>,
    },

    /// An image block (user-supplied or tool-produced).
    Image {
        /// Media type (`image/png`, `image/jpeg`, etc.).
        media_type: String,
        /// Where the image bytes live.
        source: ImageSource,
    },
}

/// Where an image block's bytes come from.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ImageSource {
    /// Inline base64 bytes.
    Base64 {
        /// The image bytes.
        data: Bytes,
    },
    /// HTTP(S) URL.
    Url {
        /// Absolute URL.
        url: String,
    },
}

/// Body of a [`ContentBlock::ToolResult`]. Anthropic allows either a plain
/// string or an array of nested blocks (for structured returns or inlined
/// images) — we mirror that via `#[serde(untagged)]`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ToolResultContent {
    /// A simple text result.
    Text(String),
    /// A structured result as a sequence of content blocks.
    Blocks(Vec<ContentBlock>),
}

impl ToolResultContent {
    /// Convenience constructor for text results.
    #[must_use]
    pub fn text(s: impl Into<String>) -> Self {
        Self::Text(s.into())
    }
}

/// One message row, fully hydrated.
///
/// `tenant_id` is denormalized from the thread so every row-level query can
/// enforce tenant isolation without a join. `parent_id` threads replies into
/// a tree, enabling forked/retried conversations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Message {
    /// Unique message identifier.
    pub id: MessageId,
    /// The thread this message belongs to.
    pub thread_id: ThreadId,
    /// Denormalized tenant ID.
    pub tenant_id: TenantId,
    /// Message author.
    pub role: Role,
    /// Message family tag.
    pub kind: MessageKind,
    /// Ordered list of content blocks.
    pub content: Vec<ContentBlock>,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Cached token count. `None` means not yet counted.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub token_count: Option<u32>,
    /// Parent message for thread forking/retries. `None` for the first row.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub parent_id: Option<MessageId>,
}

impl Message {
    /// Construct a new user message with the given text body.
    #[must_use]
    pub fn user_text(tenant_id: TenantId, thread_id: ThreadId, text: impl Into<String>) -> Self {
        Self {
            id: MessageId::new(),
            thread_id,
            tenant_id,
            role: Role::User,
            kind: MessageKind::User,
            content: vec![ContentBlock::Text { text: text.into(), cache_control: None }],
            created_at: Utc::now(),
            token_count: None,
            parent_id: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cache::{CacheControl, CacheTtl};

    fn roundtrip<T: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug>(
        value: &T,
    ) {
        let json = serde_json::to_string(value).expect("serialize");
        let back: T = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(value, &back);
    }

    #[test]
    fn role_wire_values() {
        assert_eq!(serde_json::to_value(Role::User).unwrap(), serde_json::json!("user"));
        assert_eq!(serde_json::to_value(Role::Assistant).unwrap(), serde_json::json!("assistant"));
        assert_eq!(serde_json::to_value(Role::System).unwrap(), serde_json::json!("system"));
        assert_eq!(serde_json::to_value(Role::Tool).unwrap(), serde_json::json!("tool"));
    }

    #[test]
    fn text_block_roundtrip() {
        roundtrip(&ContentBlock::Text { text: "hello".into(), cache_control: None });
    }

    #[test]
    fn text_block_with_cache_control() {
        let block = ContentBlock::Text {
            text: "hello".into(),
            cache_control: Some(CacheControl::ephemeral().with_ttl(CacheTtl::FiveMin)),
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "type": "text",
                "text": "hello",
                "cache_control": { "type": "ephemeral", "ttl": "5m" }
            })
        );
        roundtrip(&block);
    }

    #[test]
    fn thinking_block_requires_signature() {
        let block = ContentBlock::Thinking {
            thinking: "Let me think...".into(),
            signature: "sig-abc".into(),
            cache_control: None,
        };
        roundtrip(&block);
    }

    #[test]
    fn redacted_thinking_is_opaque() {
        let block = ContentBlock::RedactedThinking { data: "BASE64==".into() };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json, serde_json::json!({ "type": "redacted_thinking", "data": "BASE64==" }));
        roundtrip(&block);
    }

    #[test]
    fn tool_use_block_roundtrip() {
        let block = ContentBlock::ToolUse {
            id: ToolCallId::new(),
            name: "weather".into(),
            input: serde_json::json!({"city": "NYC"}),
            cache_control: None,
        };
        roundtrip(&block);
    }

    #[test]
    fn tool_result_text_and_blocks_both_work() {
        let text_result = ContentBlock::ToolResult {
            tool_use_id: ToolCallId::new(),
            content: ToolResultContent::text("72F sunny"),
            is_error: false,
            cache_control: None,
        };
        roundtrip(&text_result);

        let block_result = ContentBlock::ToolResult {
            tool_use_id: ToolCallId::new(),
            content: ToolResultContent::Blocks(vec![
                ContentBlock::Text { text: "see below".into(), cache_control: None },
                ContentBlock::Image {
                    media_type: "image/png".into(),
                    source: ImageSource::Url { url: "https://example.com/x.png".into() },
                },
            ]),
            is_error: false,
            cache_control: None,
        };
        roundtrip(&block_result);
    }

    #[test]
    fn tool_result_text_wire_shape_is_flat_string() {
        let block = ContentBlock::ToolResult {
            tool_use_id: ToolCallId::from_ulid(ulid::Ulid::nil()),
            content: ToolResultContent::text("ok"),
            is_error: false,
            cache_control: None,
        };
        let json = serde_json::to_value(&block).unwrap();
        assert_eq!(json["content"], serde_json::json!("ok"));
    }

    #[test]
    fn image_base64_source() {
        let block = ContentBlock::Image {
            media_type: "image/png".into(),
            source: ImageSource::Base64 { data: Bytes::from_static(b"\x89PNG\r\n") },
        };
        roundtrip(&block);
    }

    #[test]
    fn message_kind_tagged_serialization() {
        let kind =
            MessageKind::Assistant { stop_reason: Some(StopReason::ToolUse), is_api_error: false };
        let json = serde_json::to_value(&kind).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "kind": "assistant",
                "stop_reason": "tool_use",
                "is_api_error": false
            })
        );
    }

    #[test]
    fn system_message_kind_nested() {
        let kind =
            MessageKind::System(SystemMessageKind::ApiError { classified_as: "rate_limit".into() });
        let json = serde_json::to_value(&kind).unwrap();
        assert_eq!(
            json,
            serde_json::json!({
                "kind": "system",
                "system_kind": "api_error",
                "classified_as": "rate_limit"
            })
        );
        // Verify roundtrip through serde.
        let back: MessageKind = serde_json::from_value(json).unwrap();
        assert_eq!(kind, back);
    }

    #[test]
    fn user_text_helper_constructs_valid_message() {
        let tenant = TenantId::new();
        let thread = ThreadId::new();
        let msg = Message::user_text(tenant, thread, "hello");
        assert_eq!(msg.role, Role::User);
        assert_eq!(msg.tenant_id, tenant);
        assert_eq!(msg.thread_id, thread);
        assert_eq!(msg.content.len(), 1);
    }

    #[test]
    fn full_message_roundtrip() {
        let msg = Message::user_text(TenantId::new(), ThreadId::new(), "hi");
        roundtrip(&msg);
    }
}
